### ISSUE TITLE
auth: khi đăng nhập chưa trả về trường "app" theo tài khoản, hiên tại đang set mặc định là HR

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#206]

**Comment by uranussolutions** [comment]
Không cần. Mục này đã thảo luận từ trước đó lâu r. mỗi app đã có 1 màn hình login riêng nên k cần trường app làm gì nữa. Lúc trước mindset là login sẽ dùng chung cho all app nên mới cần
