### ISSUE TITLE
app-hr: lỗi load danh sách nhân viên

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#207]
![Capture](https://user-images.githubusercontent.com/66545389/133229449-c8dc1a12-ddb4-494b-8596-143482d757d5.PNG)

đăng nhập app-hr bằng quyền human-resouce (hoặc admin) nhưng vẫn không load được danh sách nhân viên, hình như báo lỗi phân quyền

**Comment by uranussolutions** [comment]
postman load bình thường
![image](https://user-images.githubusercontent.com/48413548/133311127-502d42e8-20d5-4de4-8075-f455b38c62a2.png)
