### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#214]
![Capture](https://user-images.githubusercontent.com/66545389/133358841-20bbda2f-0d05-4682-8440-bd702f33702e.PNG)
hiện tại đang dùng chung component login cần có trường app để check đườn dẫn , nếu làm login riêng thì chưa có thảo luận và chưa có issue làm login riêng

**Comment by uranussolutions** [comment]
@giahieu123456  build 2 app riêng vẫn có 2 màn hình login riêng mà
