### ISSUE TITLE
ahh-hr: template-overtime

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#218]
phiếu lương
![Capture](https://user-images.githubusercontent.com/66545389/133369561-b2c9e186-c7e9-4bdf-9100-4c676711523c.PNG)
mẫu tăng ca
![Capture1](https://user-images.githubusercontent.com/66545389/133369563-2be5b035-121b-41b7-a3d1-25f643d9fad9.PNG)
cập nhật lại mẫu tăng ca , những phiếu lương đã chọn mấu tăng ca (được cập nhật) trước đó, không cập nhật theo, vẫn giữ giá trị cũ

**Comment by uranussolutions** [comment]
Mẫu tăng ca dùng để chọn mẫu cho phiếu lương. khi chọn mẫu này nghĩa là sẽ tạo một giá trị mới tương ứng với mẫu này cho phiếu lương đó. Nên giá trị giữa mẫu và phiếu lương không được đồng bộ với nhau
