### ISSUE TITLE
app-sell : update order

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#219]
![Capture](https://user-images.githubusercontent.com/66545389/133373088-a1981253-8341-43f9-80bb-c3b7cf11ba9b.PNG)
cập nhật đơn hàng gồm nhiều trường không thành công, chỉ cập nhật thành công khi gửi duy nhất trường deliveredAt

**Comment by uranussolutions** [comment]
@giahieu123456  mấy cái này thì copy cái text đó comment vô này để t copy test lại cho nhanh nha

**Comment by uranussolutions** [comment]
@giahieu123456 commodityIds UI đâu cho set lại list này nhỉ
