### ISSUE TITLE
app-hr: template-overtime

### ISSUE THREAD

**Issue by giahieu123456** [uranussolutions/minhdu-api#252]
![Capture](https://user-images.githubusercontent.com/66545389/133965507-14d78897-e555-4277-96f3-a47dd9487e6c.PNG)
**get teamplate overtime với type mặc định của action báo lỗi từ server (bản mẫu tăng ca nên chỉ có overtime không cần search theo type)**

**Comment by uranussolutions** [comment]
@giahieu123456  type là cái action ở front end đó. trước khi gửi đi handle lại data bỏ cái action ra

**Comment by uranussolutions** [comment]
Hiện tại thì chưa cần nên t sẽ bỏ ra. nhưng mấy api khác vẫn fai handle lại k gửi cái action theo
